server:
  port: 80
  servlet:
    context-path: '/'
    session:
      timeout: 600
      cookie:
        domain: localhost
        path: '/'
    
spring:
  banner:
    charset: UTF-8
    location: 'classpath:config/banner.txt'
  profiles:
    active: local
  jackson:
    serialization:
      INDENT_OUTPUT: true
  messages:
    basename: messages/message
    encoding: UTF-8
  freemarker:
    cache: false
  jwt:
    secret: govlepel@$&

logging:
  config: 'classpath:config/logback-dev.xml'

---
# 로컬환경 
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: 'jdbc:log4jdbc:mysql://CSTALK-DEV-DB:3306/cstalk?characterEncoding=UTF-8&serverTimezone=UTC'
      username: cstalk
      password: cstalk12#$
    tomcat:
        max-active: 1
        max-idle: 1
        min-idle: 1
        max-wait: 1
        initial-size: 1
        test-on-borrow: true
        test-while-idle: true
        validation-query: select 1
        time-between-eviction-runs-millis: 3000 
  #datasource:
  #  hikari:
  #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #    jdbc-url: jdbc:log4jdbc:h2:mem:testdb;MODE=mysql;
  #    username: sa
  #    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: localhost
    port: 6379
  freemarker:
    template-loader-path: 'classpath:/templates'
    suffix: .ftl
  
server:
  port: 8080
  
domain:
  sdtalk: localhost.gasapp.co.kr
  relay: relay-scg.gasapp.co.kr
  
---
# 개발환경 
spring:
  profiles: dev

---
# 운영환경 
spring:
  profiles: live
  
logging:
  config: 'classpath:config/logback-live.xml'
  
  