server:
  port: 80
  servlet:
    context-path: '/'
    session:
      timeout: 600
      cookie:
        domain: .scglab.com
        path: '/'
    
spring:
  banner:
    charset: UTF-8
    location: 'classpath:config/banner.txt'
  profiles:
    active: local
  jackson:
    serialization:
      INDENT_OUTPUT: true
  messages:
    basename: messages/message
    encoding: UTF-8


logging:
  config: 'classpath:config/logback-dev.xml'

---
# 로컬환경 
spring:
  profiles: local
  datasource:
    hikari:
      #driver-class-name: org.h2.Driver
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:h2:mem:testdb;MODE=mysql;
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
  
server:
  port: 9091
  

---
# 개발환경 
spring:
  profiles: dev

---
# 운영환경 
spring:
  profiles: live
  
logging:
  config: 'classpath:config/logback-live.xml'
  
  