# 서버 설정.
server:
  port: 8080
  servlet:
    context-path: "/"
    session:
      timeout: 600
      cookie:
        domain: localhost
        path: "/"
  error:
    include-exception: true
    include-stacktrace: never
    path: /error/error
    whitelabel:
      enabled: false

# 스프링부트 기본 설정.
spring:
  application:
    name: 상담톡 v2.0
  banner:
    charset: UTF-8
    location: "classpath:config/banner.txt"
  profiles:
    active: local
    web-application-type: none
  redis:
    host: localhost
    port: 6379
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: .ftl
    cache: false
  main:
    web-application-type: servlet
  jackson:
    serialization:
      INDENT_OUTPUT: true
  messages:
    basename: messages/message
    encoding: UTF-8
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: "jdbc:log4jdbc:mysql://dev.gasapp.co.kr:3306/cstalk?characterEncoding=UTF-8&serverTimezone=UTC"
      username: cstalk
      password: cstalk12#$
      idle-timeout: 10000
      connection-timeout: 300000
      maximumPoolSize: 10
      minimum-idle: 5
      max-lifetime: 60000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

domain:
  cstalk: cstalk-dev.gasapp.co.kr
  cstalk-dev: cstalk-dev.gasapp.co.kr
  relay-scg: relay-scg-dev.gasapp.co.kr
  relay-vir: relay-vir-dev.gasapp.co.kr

path:
  upload: /Volumes/Data/_upload

# Prometheus 설정.
management:
  endpoints:
    web:
      base-path: /api/application
      exposure:
        #include: "prometheus"
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    address: "127.0.0.1"

# Logging 설정.
logging:
  config: "classpath:config/logback-local.xml"

relay:
  use-example: false


---
# 배포환경
spring:
  profiles: deploy

---
# 로컬환경
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

relay:
  use-example: false

---
# 개발환경1
server:
  port: 8115

spring:
  profiles: dev1
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: "jdbc:log4jdbc:mysql://127.0.0.1:3306/cstalk?characterEncoding=UTF-8&serverTimezone=UTC"
      username: cstalk
      password: cstalk12#$
      idle-timeout: 10000
      connection-timeout: 300000
      maximumPoolSize: 10
      minimum-idle: 5
      max-lifetime: 60000
      
domain:
  cstalk: cstalk-dev.gasapp.co.kr
  cstalk-dev: cstalk-dev.gasapp.co.kr
  relay-scg: relay-scg-dev.gasapp.co.kr
  relay-vir: relay-vir-dev.gasapp.co.kr

path:
  upload: /data/project/gasapp-cstalk/apache/data/attach

# Prometheus 설정.
management:
  server:
    address: "221.147.44.2"

logging:
  config: "classpath:config/logback-dev.xml"

relay:
  use-example: false

---
# 개발환경2
server:
  port: 8125

spring:
  profiles: dev2
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: "jdbc:log4jdbc:mysql://127.0.0.1:3306/cstalk?characterEncoding=UTF-8&serverTimezone=UTC"
      username: cstalk
      password: cstalk12#$
      idle-timeout: 10000
      connection-timeout: 300000
      maximumPoolSize: 10
      minimum-idle: 5
      max-lifetime: 60000
path:
  upload: /data/project/gasapp-cstalk/apache/data/attach

# Prometheus 설정.
management:
  server:
    address: "221.147.44.2"

logging:
  config: "classpath:config/logback-dev.xml"

relay:
  use-example: false

---
# 스테이지1
server:
  port: 8115

spring:
  profiles: stage1
  redis:
    host: 10.1.3.72
    port: 6379
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: "jdbc:log4jdbc:mysql://GASAPP-APP-DB:3306/cstalk?characterEncoding=UTF-8&serverTimezone=UTC"
      username: cstalk
      password: coxldtkdeka12#$
      idle-timeout: 10000
      connection-timeout: 300000
      maximumPoolSize: 10
      minimum-idle: 5
      max-lifetime: 60000

domain:
  cstalk: cstalk-stage.gasapp.co.kr
  relay-scg: relay-scg-stage.gasapp.co.kr

path:
  upload: /data/project/gasapp-cstalk/apache/data/attach

# Prometheus 설정.
management:
  server:
    address: "221.147.44.2"

# Logging 설정.
logging:
  config: "classpath:config/logback-stage.xml"

relay:
  use-example: false

---
# 스테이지2
server:
  port: 8116

spring:
  profiles: stage2
  redis:
    host: 10.1.3.72
    port: 6379
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: "jdbc:log4jdbc:mysql://GASAPP-APP-DB:3306/cstalk?characterEncoding=UTF-8&serverTimezone=UTC"
      username: cstalk
      password: coxldtkdeka12#$
      idle-timeout: 10000
      connection-timeout: 300000
      maximumPoolSize: 10
      minimum-idle: 5
      max-lifetime: 60000

domain:
  cstalk: cstalk-stage.gasapp.co.kr
  relay-scg: relay-scg-stage.gasapp.co.kr

path:
  upload: /data/project/gasapp-cstalk/apache/data/attach

# Prometheus 설정.
management:
  server:
    address: "221.147.44.2"

# Logging 설정.
logging:
  config: "classpath:config/logback-stage.xml"

relay:
  use-example: false
---
# 운영환경1
server:
  port: 8115

spring:
  profiles: live1
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: "jdbc:log4jdbc:mysql://GASAPP-APP-DB:3306/cstalk?characterEncoding=UTF-8&serverTimezone=UTC"
      username: cstalk
      password: coxldtkdeka12#$
      idle-timeout: 10000
      connection-timeout: 300000
      maximumPoolSize: 10
      minimum-idle: 5
      max-lifetime: 60000

domain:
  cstalk: cstalk.gasapp.co.kr
  relay-scg: relay-scg.gasapp.co.kr

path:
  upload: /data/project/gasapp-cstalk/apache/data/attach

# Prometheus 설정.
management:
  server:
    address: "221.147.44.2"

# Logging 설정.
logging:
  config: "classpath:config/logback-live1.xml"

relay:
  use-example: false

---
# 운영환경2
server:
  port: 8125

spring:
  profiles: live2
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: "jdbc:log4jdbc:mysql://GASAPP-APP-DB:3306/cstalk?characterEncoding=UTF-8&serverTimezone=UTC"
      username: cstalk
      password: coxldtkdeka12#$
      idle-timeout: 10000
      connection-timeout: 300000
      maximumPoolSize: 10
      minimum-idle: 5
      max-lifetime: 60000
domain:
  cstalk: cstalk.gasapp.co.kr
  relay-scg: relay-scg.gasapp.co.kr

path:
  upload: /data/project/gasapp-cstalk/apache/data/attach

# Prometheus 설정.
management:
  server:
    address: "221.147.44.2"

# Logging 설정.
logging:
  config: "classpath:config/logback-live2.xml"

relay:
  use-example: false
