server:
  port: 80
  servlet:
    context-path: '/'
    session:
      timeout: 600
      cookie:
        domain: localhost
        path: '/'
  error:
    include-exception: true
    include-stacktrace: never
    path: /error/error
    whitelabel:
      enabled: false
    
spring:
  banner:
    charset: UTF-8
    location: 'classpath:config/banner.txt'
  profiles:
    active: local
  jackson:
    serialization:
      INDENT_OUTPUT: true
  messages:
    basename: messages/message
    encoding: UTF-8
  freemarker:
    cache: false
  jwt:
    secret: #@SCGLAB_SDTALK__$$

logging:
  config: 'classpath:config/logback-dev.xml'
  

springdoc:
  cache:
    disabled: true
  version: 0.1
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: ASC


---
# 로컬환경 
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: 'jdbc:log4jdbc:mysql://CSTALK-DEV-DB:3306/cstalk?characterEncoding=UTF-8&serverTimezone=UTC'
      username: cstalk
      password: cstalk12#$
      idle-timeout: 10000
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: localhost
    port: 6379
  freemarker:
    template-loader-path: 'classpath:/templates'
    suffix: .ftl
  
server:
  port: 8080
  
domain:
  sdtalk: localhost.gasapp.co.kr
  relay: relay-scg.gasapp.co.kr
  
path:
  upload: /Volumes/Data/_upload
  
---
# 개발환경 
spring:
  profiles: dev

---
# 운영환경 
spring:
  profiles: live
  
logging:
  config: 'classpath:config/logback-live.xml'
  
  